version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comandapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3336:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
