version: '4'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comandapp
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - F:/Documentos/VolumenesDocker/dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    volumes:
      - F:/Documentos/VolumenesDocker/pma/config/.user.inc.php:/etc/phpmyadmin/config/.user.inc.php
volumes:
  dbdata:
  pma: